CREATE TABLE ESTUDIANTES(
    EST_ID_ESTUDIANTE SERIAL PRIMARY KEY,
    EST_NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE PROFESORES(
    PRO_ID_PROFESOR SERIAL PRIMARY KEY,
    PRO_NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE NOTAS(
    NOT_ID_NOTA SERIAL PRIMARY KEY,
    NOT_EST_ID_ESTUDIANTE INT NOT NULL,
    NOT_PRO_ID_PROFESOR INT NOT NULL,
    NOT_VALOR DECIMAL(4,2) NOT NULL,
    FOREIGN KEY (NOT_EST_ID_ESTUDIANTE) REFERENCES ESTUDIANTES(EST_ID_ESTUDIANTE),
    FOREIGN KEY (NOT_PRO_ID_PROFESOR) REFERENCES PROFESORES(PRO_ID_PROFESOR)
);